### ISSUE TITLE
Que scheduler does not enqueue jobs with the ruby3 branch of que

### ISSUE THREAD

**Issue by daniel-prause** [hlascelles/que-scheduler#313]
Hi there!

First of all, the ruby3 branch of que is still "bleeding edge". Since our project is based on ruby3, we ran into the following issue:
```
[#<Que::ActiveRecord::Model:0x0000000008aac3e8
  priority: 0,
  run_at: 2022-02-14 10:59:56.697444 UTC,
  id: 80428,
  job_class: "Que::Scheduler::SchedulerJob",
  error_count: 15,
  last_error_message: "TypeError: no implicit conversion of String into Hash",
  queue: "default",
  last_error_backtrace:
   "/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/job_methods.rb:51:in `_run'\n<internal:kernel>:90:in `tap'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/worker.rb:103:in `block in work_job'\n(eval):11:in `block in run_job_middleware'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/utils/middleware.rb:41:in `invoke_middleware'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/utils/middleware.rb:37:in `block in invoke_middleware'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/active_record/connection.rb:33:in `call'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/utils/middleware.rb:36:in `invoke_middleware'\n(eval):11:in `run_job_middleware'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/worker.rb:103:in `work_job'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/worker.rb:76:in `work_loop'\n/home/project/app/shared/bundle/ruby/3.0.0/bundler/gems/que-fad4c126a97a/lib/que/worker.rb:46:in `block in initialize'",
  finished_at: nil,
  expired_at: nil,
  args: [{"last_run_time"=>"2022-02-10T09:31:00+00:00", "job_dictionary"=>["MyJob"]}],
  data: {},
  kwargs: "{}">]
```

Our solution for that was:

```
# frozen_string_literal: true

# fix kwargs for que scheduler
class SchedulerKwArgs < ActiveRecord::Migration[7.0]
  def up
    execute 'ALTER TABLE public.que_jobs DISABLE TRIGGER que_scheduler_prevent_job_deletion_trigger'
    Que::ActiveRecord::Model.where(job_class: 'Que::Scheduler::SchedulerJob').destroy_all
    Que::Scheduler::Migrations.reenqueue_scheduler_if_missing
    execute 'ALTER TABLE public.que_jobs ENABLE TRIGGER que_scheduler_prevent_job_deletion_trigger'
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
```

Special thanks to @milgner for finding and fixing this with me :-)

**Comment by hlascelles** [comment]
Thank you for reporting this. I will definitely try to keep que-scheduler ruby 3 compliant.
Was this against the branch on this PR? https://github.com/que-rb/que/pull/319

I'll see if I can replicate by creating a fresh project and migrating it.

Now you've fixed it, does it "just work"?

**Comment by milgner** [comment]
> Thank you for reporting this. I will definitely try to keep que-scheduler ruby 3 compliant.
> Was this against the branch on this PR? https://github.com/que-rb/que/pull/319
> 
> I'll see if I can replicate by creating a fresh project and migrating it.
> 
> Now you've fixed it, does it "just work"?

Yes, indeed, that's the branch! After applying these changes, everything just worked as expected again.
Of course it probably makes sense to wait with publishing these changes until the corresponding changes in que itself have been published as well, but we wanted to give you a heads-up already.
