### ISSUE TITLE
undefined method `to_local_time' for #<EtOrbi::EoTime:0x00007fb9e3056e10>

### ISSUE THREAD

**Issue by jish** [hlascelles/que-scheduler#4]
I am having trouble bootstraping the Que Scheduler infrastructure. The first time I start the job scheduler, it does not exit properly:

    priority    | 0
    run_at      | 2018-03-13 18:28:52.206875-07
    job_id      | 2
    job_class   | Que::Scheduler::SchedulerJob
    args        | [{"last_run_time":"2018-03-13T23:20:46Z","job_dictionary":["FooJob"]}]
    error_count | 9
    last_error  | undefined method `to_local_time' for #<EtOrbi::EoTime:0x00007fb9e3056e10>
                | $HOME/.gem/ruby/2.4.2/gems/que-scheduler-1.0.2/lib/que/scheduler/defined_job.rb:41:in `next_run_time'
                | $HOME/.gem/ruby/2.4.2/gems/que-scheduler-1.0.2/lib/que/scheduler/defined_job.rb:50:in `calculate_missed_runs'
                | $HOME/.gem/ruby/2.4.2/gems/que-scheduler-1.0.2/lib/que/scheduler/enqueueing_calculator.rb:26:in `block in parse'
                | $HOME/.gem/ruby/2.4.2/gems/que-scheduler-1.0.2/lib/que/scheduler/enqueueing_calculator.rb:17:in `each'
                | $HOME/.gem/ruby/2.4.2/gems/que-scheduler-1.0.2/lib/que/scheduler/enqueueing_calculator.rb:17:in `parse'

I'm running

```ruby
Que::Scheduler::SchedulerJob.enqueue
```

according to the Readme.

**Comment by jish** [comment]
It looks like the `to_local_time` method was not added until version `1.0.6` of `et-orbi`, and `que-scheduler` only depends on `>= 1.0.5` via a transitive dependency on `fugit` https://github.com/floraison/fugit/blob/8736fc4dcdb8002bffab3c07613d205a89afbea7/fugit.gemspec#L32

* It looks like `que-scheduler` can either define its own dependency on `et-orbi` `> 1.0.5` since `que-scheduler` depends on methods in later versions.
* Or we could get `fugit` to define a more specific dependency.

I think the more straightforward fix is to define the dependency here because the way the two libraries are being used in conjunction with each other here creates the dependency. I can open a pull request if you like.
